# Generated by Django 4.2.7 on 2023-12-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_blog_remove_product_created_at_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publication_sign',
            field=models.BooleanField(default=True, verbose_name='признак публикации'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
