# Generated by Django 4.2.7 on 2023-12-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_blog_publication_sign_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publication_sign',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='признак публикации'),
        ),
    ]
